name: cobalt_annotations
description: Annotations for Cobalt — @CobaltInject, @injected, @CobaltBootstrap, @CobaltInit and @CobaltScopeRoot.
version: 0.1.1
repository: https://github.com/rutikeyone/cobalt
issue_tracker: https://github.com/rutikeyone/cobalt/issues
topics:
  - dependency-injection
  - annotations
  - codegen
  - di

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  meta: ^1.16.0
