"""The class modifiers of every public type, written down.

    python3 tool/modifiers.py           # rewrite tool/class_modifiers.txt
    python3 tool/modifiers.py --check   # fail if it is stale (CI)

A class modifier is API. `interface` to `base` stops every `implements` of it
compiling, `final` stops every `extends`, and dropping `sealed` ends every
exhaustive switch — yet dart_apitool (tool/api.sh) did not notice when
CobaltResolver went from one to the other. So the modifiers are kept in a
file, one public type a line, and a change to one is a changed line in review
that CI will not let through unrecorded. Whether that line is breaking is the
question RELEASING's table of types answers.

Reads source, not the analyzer: each package's public libraries are the Dart
files directly under lib/, a public type is one they declare or export (with
`show` and `hide` honoured) whose name does not start with an underscore, and
`part` files belong to the library that names them. That is all this
repository's layout needs; a declaration this cannot parse fails loudly
rather than being skipped.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'tool' / 'class_modifiers.txt'
HEADER = (
  '# Generated by tool/modifiers.py. Do not edit.\n'
  '# declaring package  type  kind and modifiers\n'
)

DIRECTIVE = re.compile(
  r"^(export|part)\s+'([^']+)'((?:\s+(?:show|hide)\s+[\w\s,]+?)*)\s*;", re.M
)
COMBINATOR = re.compile(r'(show|hide)\s+([\w\s,]+?)(?=\s+(?:show|hide)\b|$)')
# A top-level declaration starts in column 0. Annotations and doc comments sit
# on the lines above it, so anchoring on the line start is enough.
DECLARATION = re.compile(
  r'^((?:(?:abstract|base|interface|final|sealed|mixin)\s+)*)'
  r'(class|mixin|enum|typedef|extension\s+type|extension)\b\s*(\w*)',
  re.M,
)


def package_of(path: pathlib.Path) -> str:
  return path.relative_to(ROOT / 'packages').parts[0]


def resolve(uri: str, base: pathlib.Path) -> pathlib.Path:
  if uri.startswith('package:'):
    package, rest = uri[len('package:'):].split('/', 1)
    return ROOT / 'packages' / package / 'lib' / rest
  return (base.parent / uri).resolve()


def names_allowed(combinators: str):
  shown, hidden = None, set()
  for kind, names in COMBINATOR.findall(combinators.strip()):
    listed = {n.strip() for n in names.split(',') if n.strip()}
    if kind == 'show':
      shown = listed if shown is None else shown & listed
    else:
      hidden |= listed
  return lambda name: (shown is None or name in shown) and name not in hidden


def declared(path: pathlib.Path) -> dict[str, str]:
  """Public types declared in [path] and its parts: name -> kind."""
  text = path.read_text()
  types = {}
  for modifiers, keyword, name in DECLARATION.findall(text):
    kind = ' '.join(modifiers.split() + keyword.split())
    if not name:
      if keyword == 'extension':  # an unnamed extension is not a type
        continue
      sys.exit(f'{path}: cannot read the name of a `{kind}` declaration')
    if not name.startswith('_'):
      types[name] = kind
  for directive, uri, _ in DIRECTIVE.findall(text):
    if directive == 'part':
      types.update(declared(resolve(uri, path)))
  return types


def exported(library: pathlib.Path, seen=None) -> dict[str, tuple[str, str]]:
  """Public types [library] makes visible: name -> (kind, declaring package)."""
  seen = set() if seen is None else seen
  if library in seen:
    return {}
  seen.add(library)
  text = library.read_text()
  types = {
    name: (kind, package_of(library)) for name, kind in declared(library).items()
  }
  for directive, uri, combinators in DIRECTIVE.findall(text):
    if directive != 'export':
      continue
    allowed = names_allowed(combinators)
    for name, entry in exported(resolve(uri, library), seen).items():
      if allowed(name):
        types[name] = entry
  return types


def main() -> int:
  # Keyed by the package that declares the type, not the one that exports it:
  # cobalt_flutter re-exports all of cobalt, and a modifier changed in cobalt
  # should read as one changed line, not three.
  public = {}
  for package_dir in sorted((ROOT / 'packages').iterdir()):
    lib = package_dir / 'lib'
    if not lib.is_dir():
      continue
    for library in sorted(lib.glob('*.dart')):
      for name, (kind, home) in exported(library).items():
        public[(home, name)] = kind
  lines = [f'{home}  {name}  {kind}' for (home, name), kind in sorted(public.items())]

  body = HEADER + '\n'.join(lines) + '\n'
  current = OUT.read_text() if OUT.exists() else None
  if current == body:
    return 0
  if '--check' in sys.argv[1:]:
    print(
      f'{OUT.relative_to(ROOT)} is stale — a public type was added, removed '
      'or changed its modifiers. Run `python3 tool/modifiers.py` and review '
      'the diff against the table of types in RELEASING.md.'
    )
    return 1
  OUT.write_text(body)
  return 0


if __name__ == '__main__':
  sys.exit(main())
