import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HEADER = '# Generated by tool/overrides.py. Do not edit.\n'


def main() -> int:
  check = '--check' in sys.argv[1:]
  members = subprocess.run(
    [str(ROOT / 'tool' / 'members.sh')], check=True, capture_output=True, text=True
  ).stdout.split()

  where = {}
  for member in members:
    pubspec = (ROOT / member / 'pubspec.yaml').read_text()
    where[re.search(r'^name: (\S+)', pubspec, re.M).group(1)] = member
  packages = [name for name, path in where.items() if not path.startswith('compat/')]

  def named_by(name: str) -> set[str]:
    text = (ROOT / where[name] / 'pubspec.yaml').read_text()
    return {
      other for other in packages
      if other != name and re.search(rf'^  {other}:', text, flags=re.M)
    }

  direct = {name: named_by(name) for name in where}
  stale = []
  for name, member in where.items():
    if member.startswith('compat/'):
      continue
    reachable = set(direct[name])
    while True:
      grown = reachable | {n for r in reachable for n in direct[r]}
      if grown == reachable:
        break
      reachable = grown
    reachable.discard(name)

    body = None
    if reachable:
      body = HEADER + 'dependency_overrides:\n' + ''.join(
        f'  {other}:\n    path: {os.path.relpath(where[other], member)}\n'
        for other in sorted(reachable)
      )

    target = ROOT / member / 'pubspec_overrides.yaml'
    current = target.read_text() if target.exists() else None
    if current == body:
      continue
    stale.append(member)
    if check:
      continue
    if body is None:
      target.unlink()
    else:
      target.write_text(body)

  if check and stale:
    print('pubspec_overrides.yaml is out of date in: ' + ', '.join(stale))
    print('run: python3 tool/overrides.py')
    return 1
  return 0


if __name__ == '__main__':
  raise SystemExit(main())
