name: codegen_basics
description: Code-Gen Mode showcase.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

resolution: workspace

dependencies:
  cobalt: ^0.2.0
  cobalt_flutter: ^0.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  cobalt_generator: ^0.2.0
  cobalt_lint: ^0.2.0
  build_runner: ^2.15.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
